compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard # used for multiple nodes training
  gradient_accumulation_steps: 4
  offload_optimizer_device: cpu  # save GPU memory, but need more time
  offload_param_device: cpu  # save GPU memory, but need more time
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 2
num_processes: 4 # number of all gpus 
main_process_ip: 0.0.0.0
main_process_port: 7777
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
